spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/demo001
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

---

logging:
  level:
    "liquibase" : debug

spring:
  liquibase:
#    enabled: true
#    contexts: dev
    change-log: "classpath*:db/liquibase.yml"
